<?php // /php/doctrine-dbal/tests/Unit/IsolationRefusalTest.php
declare(strict_types=1);
namespace Ferro\DBAL\Tests\Unit;

use Doctrine\DBAL\Platforms\MySQL84Platform;
use Doctrine\DBAL\Platforms\PostgreSQL120Platform;
use Doctrine\DBAL\TransactionIsolationLevel;
use Ferro\DBAL\Exception\UnsupportedStatement;
use Ferro\DBAL\Wrapper\FerroConnection;
use Ferro\Protocol\Isolation;
use PHPUnit\Framework\TestCase;

/**
 * M1-S8b Task 13 — the isolation statement, refused; and the level, mapped.
 *
 * The strings the refusal matches are NOT invented here: they are generated by the STOCK platforms
 * below, so a DBAL release that changes their wording makes this test red instead of silently
 * turning the refusal into a no-op — which would restore the silent wrong-isolation bug.
 */
final class IsolationRefusalTest extends TestCase
{
    /** @return array<string, array{0: string}> */
    public static function stockIsolationSql(): array
    {
        $out = [];
        foreach (TransactionIsolationLevel::cases() as $level) {
            $out['pg ' . $level->name] = [(new PostgreSQL120Platform())->getSetTransactionIsolationSQL($level)];
            $out['mysql ' . $level->name] = [(new MySQL84Platform())->getSetTransactionIsolationSQL($level)];
        }
        return $out;
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('stockIsolationSql')]
    public function testEveryStockIsolationStatementIsRecognised(string $sql): void
    {
        self::assertTrue(
            FerroConnection::isIsolationStatement($sql),
            "the driver must recognise the statement Doctrine actually emits: $sql",
        );
    }

    /** …and nothing else is. A refusal that fired on ordinary SQL would be far worse than the bug. */
    public function testOrdinarySqlIsNotMistakenForIt(): void
    {
        foreach ([
            'SELECT 1',
            "UPDATE t SET note = 'SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE'",
            'SET LOCAL statement_timeout = 100',
            "INSERT INTO log (msg) VALUES ('SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED')",
        ] as $sql) {
            self::assertFalse(FerroConnection::isIsolationStatement($sql), "must NOT match: $sql");
        }
    }

    public function testTheRefusalNamesTheWrapperAsTheFix(): void
    {
        $e = UnsupportedStatement::isolation('SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE');
        self::assertStringContainsString('wrapperClass', $e->getMessage());
        self::assertStringContainsString(FerroConnection::class, $e->getMessage());
    }

    /**
     * The `TransactionIsolationLevel` → `Ferro\Protocol\Isolation` mapping, DERIVED from the DBAL
     * enum so a new case fails here rather than being silently dropped.
     *
     * `READ_UNCOMMITTED` maps to `ReadCommitted`, which is what `Ferro\Protocol\Isolation`'s own
     * docblock specifies (PostgreSQL treats them as the same level). On MySQL that is a genuine
     * UPGRADE to a stricter level — never a weaker one — and it is listed in
     * `docs/known-incompatibilities.md`.
     */
    public function testEveryDbalLevelMaps(): void
    {
        $expected = [
            'READ_UNCOMMITTED' => Isolation::ReadCommitted,
            'READ_COMMITTED' => Isolation::ReadCommitted,
            'REPEATABLE_READ' => Isolation::RepeatableRead,
            'SERIALIZABLE' => Isolation::Serializable,
        ];
        foreach (TransactionIsolationLevel::cases() as $case) {
            self::assertArrayHasKey($case->name, $expected, "unmapped TransactionIsolationLevel::{$case->name}");
            self::assertSame($expected[$case->name], FerroConnection::toFerroIsolation($case));
        }
    }
}
