<?php // /php/doctrine-dbal/tests/Unit/TransactionRoutingTest.php
declare(strict_types=1);
namespace Ferro\DBAL\Tests\Unit;

use Doctrine\DBAL\Connection as DbalConnection;
use Ferro\Client\Connection as FerroClientConnection;
use Ferro\DBAL\Connection as FerroDriverConnection;
use Ferro\DBAL\PlatformVersion;
use Ferro\DBAL\Tests\Support\FixedDriver;
use Ferro\Protocol\ExecRequest;
use Ferro\Protocol\Generated\Constants as C;
use Ferro\Protocol\Msgpack\PurePacker;
use Ferro\Tests\Support\FakeSession;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * M1-S8b Task 10 — the driver connection's most important internal invariant, asserted at the ONE
 * vantage point where the mechanism itself is visible: the ENCODED `ExecRequest`.
 *
 * `TransactionLiveTest` proves the CONSEQUENCE end to end (the inner rollback undoes only the inner
 * write, so the SAVEPOINT must have been created in the same session as the BEGIN). This tier proves
 * the MECHANISM: that the `SAVEPOINT …` statement Doctrine generates literally carries the pinned
 * `tx_id` on the wire. That is M1-S8b Task 1's shape
 * (`Ferro\Tests\Unit\RawFetchTest::testInsideATransactionItCarriesThePinnedTxId`) applied to the
 * statement DOCTRINE writes rather than one the test writes.
 *
 * Everything above the driver SPI here is the real `Doctrine\DBAL\Connection`: its client-side
 * nesting counter, its savepoint naming, its `executeStatement()` routing and the stock platform's
 * savepoint SQL. Only the transport is fake ({@see FakeSession}), which is what makes the wire
 * payload readable at all.
 */
final class TransactionRoutingTest extends TestCase
{
    /**
     * Decode a recorded `ExecRequest` payload back to its field map.
     *
     * `PurePacker`, never `ExtPacker`: the latter consumes the whole buffer regardless of the offset
     * it is handed, so an offset-based decode silently reads the wrong frame (plan hazard 87). This
     * is `ConnectionImperativeTxTest`'s idiom.
     *
     * @return array<string,mixed>
     */
    private static function decodeExec(string $payload): array
    {
        $off = 0;
        $w = (new PurePacker())->unpack($payload, $off);
        return ExecRequest::mapFromWire((array) $w);
    }

    /** @return array<string, array{0: string, 1: string}> family => [kind, the server version string] */
    public static function families(): array
    {
        return [
            'postgres' => [PlatformVersion::KIND_POSTGRES, '17.10'],
            'mysql' => [PlatformVersion::KIND_MYSQL, '8.4.11'],
        ];
    }

    /**
     * A `Doctrine\DBAL\Connection` whose driver connection is ours, over `$session`.
     *
     * `serverVersion` in the params is what lets `getDatabasePlatform()` resolve without a
     * connection (plan hazard 15) — `createSavepoint()` needs a platform to generate its SQL.
     */
    private static function dbal(FakeSession $session, string $kind, string $version): DbalConnection
    {
        $driverConn = new FerroDriverConnection(
            new FerroClientConnection(session: $session),
            'default',
            $kind,
            false,
        );
        return new DbalConnection(['serverVersion' => $version], new FixedDriver($driverConn, $kind));
    }

    /**
     * THE guard. Doctrine nests transactions CLIENT-SIDE: only level 1 reaches the driver's
     * `beginTransaction()`, and level 2 is an ordinary `executeStatement($platform->createSavePoint(…))`.
     * On a transaction-mode pool a statement that did not carry the `tx_id` would be checked out onto
     * a DIFFERENT backend connection, so the SAVEPOINT would be created in a session that knows
     * nothing about the BEGIN.
     */
    #[DataProvider('families')]
    public function testDoctrinesSavepointStatementCarriesThePinnedTxId(string $kind, string $version): void
    {
        $session = FakeSession::withTxBegin(txId: 41)->thenExecOk()->thenExecOk()->thenControlOk();
        $c = self::dbal($session, $kind, $version);

        $c->beginTransaction();                    // level 1 -> the driver's beginTransaction()
        $c->beginTransaction();                    // level 2 -> SAVEPOINT, as an ORDINARY statement
        self::assertSame(2, $c->getTransactionNestingLevel(), "[$kind] Doctrine nests client-side");

        // The expected SQL is generated by the STOCK platform, not spelled here — so a Doctrine
        // release that changes the wording makes this red rather than silently comparing nothing.
        $expectedSql = $c->getDatabasePlatform()->createSavePoint('DOCTRINE_2');

        $req = self::decodeExec($session->lastRequest()['payload']);
        self::assertSame($expectedSql, $req['sql'], "[$kind] the savepoint statement reached the engine");
        self::assertSame(
            41,
            $req['tx_id'],
            "[$kind] the SAVEPOINT must ride the pinned tx_id — without it Doctrine holds a rollback "
            . 'point that exists in no session',
        );

        $c->rollBack();                            // level 2 -> ROLLBACK TO SAVEPOINT
        $req = self::decodeExec($session->lastRequest()['payload']);
        self::assertSame(
            $c->getDatabasePlatform()->rollbackSavePoint('DOCTRINE_2'),
            $req['sql'],
            "[$kind] the savepoint rollback reached the engine",
        );
        self::assertSame(41, $req['tx_id'], "[$kind] and it too must ride the pinned tx_id");

        $c->commit();                              // level 1 -> the driver's commit()
    }

    /**
     * The MIRROR, without which the assertion above cannot distinguish "routes through the open
     * transaction" from "always stamps a tx_id": before the BEGIN and after the COMMIT the very same
     * statement path must carry a NULL `tx_id`.
     */
    public function testTheSameStatementPathCarriesNoTxIdOutsideATransaction(): void
    {
        $session = FakeSession::withExecOk()          // 1: before any transaction
            ->push(FakeSession::beginOk(77), [C::SERVICE_TX, C::METHOD_TX_BEGIN])
            ->thenExecOk()                            // 3: inside
            ->thenControlOk()                         // 4: COMMIT
            ->thenExecOk();                           // 5: after
        $c = self::dbal($session, PlatformVersion::KIND_POSTGRES, '17.10');

        $c->executeStatement('UPDATE t SET n = 1');
        self::assertNull(self::decodeExec($session->lastRequest()['payload'])['tx_id'], 'before BEGIN');

        $c->beginTransaction();
        $c->executeStatement('UPDATE t SET n = 2');
        self::assertSame(77, self::decodeExec($session->lastRequest()['payload'])['tx_id'], 'inside');

        $c->commit();
        $c->executeStatement('UPDATE t SET n = 3');
        self::assertNull(
            self::decodeExec($session->lastRequest()['payload'])['tx_id'],
            'after COMMIT the connection must be back on the autocommit path',
        );
    }

    /**
     * ONE `TX/BEGIN` frame reaches the engine however deep Doctrine nests — the other half of
     * "Doctrine nests client-side".
     *
     * **Read this as a PREMISE LOCK, not as a guard on our own code**: the branch it pins lives in
     * `Doctrine\DBAL\Connection::beginTransaction()`, and the entire savepoint design rests on it.
     * Ferro cannot nest transactions at all — `Ferro\Client\Connection::begin()` refuses a second
     * one — so a Doctrine release that forwarded every level to the driver would break this tier
     * outright, and it should break HERE, in a millisecond, rather than in an application.
     * Falsifiability confirmed by simulating exactly that upstream change (vendor
     * `beginTransaction()` patched to call the driver at every level): all three routing tests go
     * RED with `InvalidTransactionStateException: a transaction is already open on this connection`.
     */
    public function testOnlyNestingLevelOneReachesTheEngine(): void
    {
        $session = FakeSession::withTxBegin(txId: 5)->thenExecOk()->thenExecOk()->thenControlOk();
        $c = self::dbal($session, PlatformVersion::KIND_POSTGRES, '17.10');

        $c->beginTransaction();
        $c->beginTransaction();
        $c->beginTransaction();
        self::assertSame(3, $c->getTransactionNestingLevel());

        $frames = array_map(
            static fn (array $s): array => [$s[0], $s[1]],
            $session->sent,
        );
        self::assertSame(
            [
                [C::SERVICE_TX, C::METHOD_TX_BEGIN],
                [C::SERVICE_SQL, C::METHOD_SQL_EXEC],
                [C::SERVICE_SQL, C::METHOD_SQL_EXEC],
            ],
            $frames,
            'exactly one TX/BEGIN, then two ordinary SAVEPOINT statements',
        );
    }
}
